services:
  mcplanmanager:
    # 使用与生产环境相同的构建上下文
    build: .
    # 使用不同的容器名称，以避免与生产容器冲突
    container_name: mcplanmanager_dev_service
    # 映射端口
    ports:
      - "6276:6276"
    # 定义环境变量
    environment:
      - PORT=6276
    # 使用 uvicorn 并开启 --reload 标志，以实现代码自动重载
    command: uvicorn mcplanmanager.app:mcp --host 0.0.0.0 --port 6276 --reload
    # 核心区别：添加 volumes 映射，将本地源代码链接到容器中
    # 这使得本地代码的任何修改都能即时在容器内生效
    volumes:
      - ./mcplanmanager:/app/mcplanmanager
      - ./my-plans:/app/plans

networks:
  default:
    name: mcplanmanager_dev_net 