# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.11-slim

# set workdir
WORKDIR /app

# Copy project files
COPY . /app

# Install dependencies
RUN pip install --no-cache-dir .

# Expose nothing (stdio)
# Command
CMD ["python3", "-m", "mcplanmanager.app"]
