services:
  mcplanmanager:
    # 使用当前目录下的 Dockerfile 进行构建
    build: .
    # 给容器起一个固定的名字
    container_name: mcplanmanager_service
    # 将主机的 8080 端口映射到容器的 8080 端口 (SSE 默认端口)
    ports:
      - "8080:8080"
    # 设置环境变量来配置 SSE 模式
    environment:
      - MCP_TRANSPORT=sse
      - MCP_HOST=0.0.0.0
      - MCP_PORT=8080
    # 使用默认的 mcplanmanager 命令，它会读取环境变量
    command: mcplanmanager
    # 将本地的 my-plans 目录挂载到容器的 /app/plans 目录
    # 这样计划文件就可以持久化保存了
    volumes:
      - ./my-plans:/app/plans
    # 保持容器在前台运行，方便查看日志
    tty: true
    stdin_open: true 